FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install --no-install-recommends -y \
    # download engines
    curl ca-certificates \
    # essential tools
    git unzip sudo \
    # toolchain
    build-essential gfortran pkg-config \
    # Any package that needs a display (e.g. Gtk.jl)
    xvfb \
    # clean-up
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /storage /cache

COPY ./entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
